import Head from 'next/head'
import Link from "next/link";

import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";
import { Auth, withSSRContext } from "aws-amplify";
import { serializeModel } from "@aws-amplify/datastore/ssr"
import { Blog } from "../src/models";

export async function getServerSideProps({req}) {
  const SSR = withSSRContext({req})
  let blogData
  try {
    blogData = await SSR.DataStore.query(Blog)
  } catch (e) {
    console.error(e)
  }

  return { props: {blogs: serializeModel(blogData)}}
}

export default function Home({blogs}) {
  const [user, setUser] = useState()
  const [isAdmin, setIsAdmin] = useState(false)

  useEffect(() => {
    const getUser = async () => {
      try {
        const user = await Auth.currentAuthenticatedUser()
        setUser(user)
        console.log('dup', user.getSignInUserSession().getAccessToken().payload)
        setIsAdmin(user.getSignInUserSession().getAccessToken().payload['cognito:groups'].includes('admin'))
      } catch (e) {
        console.log(e)
      }
    }
    getUser()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? <button onClick={async () => {
        await Auth.signOut()
        setUser(null)
      } }>Sign out</button> : <Link href="/sign-in">Sign in</Link> }
      {blogs.map((blog) => <h1 key={blog.id}>{blog.name}</h1>)}
      {isAdmin && <h2>You are an Admin</h2>}
    </div>
  )
}
